Prefix: '&7[&c&l►&7]&r'

# Lưu ý: học kĩ RegEx trước khi config!
# Còn nếu bạn không biết về RegEx thì vui lòng dùng theo config mẫu!
Advertise-Characters-RegEx:
- '\[\.'
- '\.\]'
- '\(\.'
- '\.\)'
- '(\[)'
- '(\])'
- '\/'
- '(\s\.)'
- '(\.\s)'
- '(\s)'
- '(\.)'
- '(\,)'
- '(\-)'

# Phần này là kiểm tra đuôi tên miền!
Advertise-Domain-List:
- '.com'
- '.c.om'
- '.co.m'
- '.c.o.m'
- '.net'
- '.n.et'
- '.ne.t'
- '.n.e.t'
- '.vn'
- '.v.n'
- '.org'
- '.o.r.g'
- '.or.g'
- '.o.rg'
- '.tk'
- '.ml'
- '.ga'
- '.ddns'

Advertise-Domain-WhiteList:
- 'facebook.com'
- 'minevuive.com'

# Phần này là kiểm tra IP số!
# Không hiểu về RegEx vui lòng không sửa lại!
Advertise-RegEx:
- '\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}'

# Phần này là chặn không cho gữi thông điệp chứa nội dung quảng cáo!
Cancelled: true

Commands-Punish:
# CONSOLE là lệnh được gữi từ console
# MESSAGE là tin nhắn gữi tới người quảng cáo, chỉ người quảng cáo thấy!
- 'CONSOLE: kick {player} &cVui lòng không quảng cáo máy chủ!'
- 'MESSAGE: Bạn không có quyền quảng cáo chủ tại đây!'

messages:
  help:
  - '&7'
  - '&f&m                                               '
  - '&b/{lenh} [help, ?] &7- xem thêm về lệnh, quyền: ''aa.help'''
  - '&b/{lenh} info &7- xem thông tin plugin, quyền: ''aa.info'''
  - '&b/{lenh} [reload, rl] &7- nạp lại config, quyền: ''aa.reload'''
  - '&f&m                                               '
  - '&7'
  
  reload-error: '&cCó lỗi xảy ra trong quá trình reload'
  reload-success: '&aReload thành công'
  no-permission: '&cBạn không có quyền dùng lệnh này!'
  must-be-player: '&cBạn phải là người chơi để dùng lệnh này!'